language: cpp
script:
- cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
- cmake --build _build
- cmake --build _build --target install
addons:
  apt:dasdasdsad
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
